"""Added last_update attribute

Revision ID: e37e37e08ee7
Revises: cea74d01640c
Create Date: 2026-04-30 19:29:43.007397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e37e37e08ee7'
down_revision: Union[str, Sequence[str], None] = 'cea74d01640c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('last_update', sa.Date(), nullable=True))
    op.add_column('post', sa.Column('last_update', sa.Date(), nullable=True))
    op.add_column('post_fav', sa.Column('last_update', sa.Date(), nullable=True))
    op.add_column('post_tags', sa.Column('inserted_on', sa.Date(), nullable=False))
    op.add_column('post_tags', sa.Column('last_update', sa.Date(), nullable=True))
    op.drop_column('post_tags', 'date')
    op.add_column('profile', sa.Column('last_update', sa.Date(), nullable=True))
    op.add_column('rol', sa.Column('last_update', sa.Date(), nullable=True))
    op.add_column('tag', sa.Column('last_update', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('last_update', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_update')
    op.drop_column('tag', 'last_update')
    op.drop_column('rol', 'last_update')
    op.drop_column('profile', 'last_update')
    op.add_column('post_tags', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('post_tags', 'last_update')
    op.drop_column('post_tags', 'inserted_on')
    op.drop_column('post_fav', 'last_update')
    op.drop_column('post', 'last_update')
    op.drop_column('category', 'last_update')
    # ### end Alembic commands ###
